language: android
android:
  components:
    - android-20
script:
  - ./gradlew assembleRelease
  - openssl aes-256-cbc -K $encrypted_d7523b81c6ba_key -iv $encrypted_d7523b81c6ba_iv -in secure/private.key.enc -out secure/private.key -d
  - ls secure
