language: android
android:
  components:
    - android-20
script:
  - ./gradlew build
  - openssl aes-256-cbc -K $encrypted_d7523b81c6ba_key -iv $encrypted_d7523b81c6ba_iv -in private.key.enc -out private.key -d
  - ls secure
