language: android
android:
  components:
    - android-20
script:
  - ./gradlew assembleRelease
  - openssl aes-256-cbc -K $encrypted_d7523b81c6ba_key -iv $encrypted_d7523b81c6ba_iv -in secure/private.key.enc -out secure/private.key -d #秘密鍵を復元
  - openssl rsautl -inkey secure/private.key -in secure/shoma2da_key.secret -decrypt -out secure/shoma2da_key #keystoreを復元
  - ls secure
